name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 🚀

        **Before you start:** Please search existing issues to see if someone already suggested this feature.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem or need this feature would address
      placeholder: I'm always frustrated when... / I need to be able to...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the feature you'd like
      description: A clear description of what you want to happen
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

